### ISSUE TITLE
Any plans to support RAML 1.0?

### ISSUE THREAD

**Issue by sichvoge** [SmartBear/soapui-raml-plugin#16]
Hi guys,

are there any plans to support RAML 1.0?

Cheers.

**Comment by olensmar** [comment]
of course, we'll eventually get to this - sorry to keep you waiting. Please feel free to help :-)

**Comment by sichvoge** [comment]
Thanks Ole, I am not the one you want to mess up that wonderful implementation ;) However, I can help with any details you need moving forward.

**Comment by sichvoge** [comment]
@olensmar any news :) curious and looking forward to evangelize API lifecycles using SOAPUI as the testing framework :)

**Comment by mattihjelm** [comment]
@sichvoge Hi Christian, support for RAML 1.0 is in the works. It will be done soon, it is actually in testing phase now.

**Comment by sichvoge** [comment]
Looking forward to that ;)

**Comment by rdmin** [comment]
Hey guys, any news on this or any kind of ETA? I'm really interested in RAML 1.0 and i'd love to use SOAPUI as the testing framework.

**Comment by IlyaAvdeev** [comment]
hi, @rdmin, thanks for your interest in SoapUI testing framework. RAML 1.0 support will be released together with Ready! API 2.0 version. Unfortunately there is no final release date for 2.0. Currently we think it will happen at the beginning of April.

**Comment by slavashvets** [comment]
Any updates?

**Comment by IlyaAvdeev** [comment]
could you please check this https://drive.google.com/open?id=0B8zQGZrYgudeTldlSFdtYS1rdWs
we'll update the plugin repo soon. Please let me know the results

**Comment by sichvoge** [comment]
@IlyaAvdeev I can't install the plugin. SoapUI logs shows me the following

![image](https://user-images.githubusercontent.com/498114/27591086-8ff9e040-5b48-11e7-9f71-37b2dd92d1fe.png)

**Comment by IlyaAvdeev** [comment]
@sichvoge are you SoapUI OS user?

**Comment by sichvoge** [comment]
Yes, just downloaded the open source version and installed it on my Mac.

**Comment by IlyaAvdeev** [comment]
Sorry, I thought you're ReadyAPI user. I'll get it signed it soon and provide to you.

**Comment by IlyaAvdeev** [comment]
Hi, All! please try this http://productextensions.s3.amazonaws.com/SoapUI-Plugins/soapui-raml-plugin-1.3.2-dist.jar, it's signed and should work for both - SoapUI OS/ReadyAPI

**Comment by cmatthae** [comment]
Hi Ilya, 
I downloaded the jar above from amazonaws and saved it in ...\cmatthae\.soapuios\plugins. 

Unfortunately I get the same error message that sichvoge described: 
"Wed Jul 19 15:34:56 CEST 2017:ERROR:An error occurred [The plugin 'C:\Users\cmatthae\.soapuios\plugins\soapui-raml-plugin-1.3.2-dist.jar' has unsigned class files.], see error log for details.
Wed Jul 19 15:34:51 CEST 2017:WARN:Plugin 'soapui-raml-plugin-1.3.2-dist.jar' is not loaded because it hasn't been signed by SmartBear Software."
in the SoapUI log (5.3.0).

Any idea what went wrong?

Best regards

**Comment by IlyaAvdeev** [comment]
Hi, cmatthae, that's true, something went wrong. Hold on, researching... I'll be back with the solution ASAP

**Comment by IlyaAvdeev** [comment]
guys, please check once again, now it works for me
![image](https://user-images.githubusercontent.com/7438227/28409007-fc9f0fda-6d41-11e7-9966-593856bf3daa.png)

**Comment by cmatthae** [comment]
Hello Ilya,

thank you for your fast reply!
The signature problem is solved and the import is working. resourcetypes are supported - a 1.0 feature as far as I know!?

I don't want to be greedy but what about the export ;-)
I imported a raml-1.0-file into SoapUI using "Import RAML Definition" but when I exported it using "Export RAML" it still generates raml 0.8 with this deprecated baseUriParameters-tag.
Or do I overlooked something?

Best regards.

**Comment by IlyaAvdeev** [comment]
Hi, I'm happy it works for you now. We new about export problem when the plugin was made. As far as I know it was a problem on raml dependencies side, also just a couple of days ago there was a rumor it's fixed. So I believe it will become a part of next plugin version (don't know the exact date atm, sorry, but definitely it will be)

**Comment by sichvoge** [comment]
@IlyaAvdeev you can get in touch with me if there are problems with something in RAML. Let me know!

**Comment by manojduvvuri** [comment]
Is there a possibility for the source code of the plugin version 1.3.2 to be made available as well please?

**Comment by joao-a-cruz** [comment]
Hey.

I downloaded the jar from the above link but I still get the unsigned error. Any suggestions?

Thx!

**Comment by LeonidRosin** [comment]
Hey!
Any news about RAML 1.0 support? 
I'm very interested, but SoapUI 5.4.0 still does not support RAML 1.0
